apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Frontend
  - base/fe-node/image-builder.yaml
  - base/fe-node/deployment-config.yaml
  - base/fe-node/service.yaml
  - base/fe-node/route.yaml